name: Pulpo Paul Diario

on:
  workflow_dispatch:
  schedule:
    # 1. Apertura Europa -> 08:13 hrs (Hora Local Chile)
    - cron: '13 8 * * *'
      timezone: 'America/Santiago'
    
    # 2. Previa Champions/Tarde Europa -> 12:17 hrs (Hora Local Chile)
    - cron: '17 12 * * *'
      timezone: 'America/Santiago'

    # 3. Previa Latam/Libertadores -> 16:13 hrs (Hora Local Chile)
    - cron: '13 16 * * *'
      timezone: 'America/Santiago'

    # 4. Cierre del día y recálculo -> 21:17 hrs (Hora Local Chile)
    - cron: '17 21 * * *'
      timezone: 'America/Santiago'

jobs:
  analizar_partidos:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Descargar el repositorio
        uses: actions/checkout@v5

      - name: Instalar Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar el Pulpo Paul
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          API_FOOTBALL_KEY: ${{ secrets.API_FOOTBALL_KEY }}
          API_BASKETBALL_KEY: ${{ secrets.API_BASKETBALL_KEY }}
          TELEGRAM_BOT_TOKEN_BASKET: ${{ secrets.TELEGRAM_BOT_TOKEN_BASKET }}
          PROXY_URL: ${{ secrets.PROXY_URL }}
          TELEGRAM_KPI_CHAT_ID: ${{ secrets.TELEGRAM_KPI_CHAT_ID }}
          TELEGRAM_KPI_BOT_TOKEN: ${{secrets.TELEGRAM_KPI_BOT_TOKEN }} 
        run: python main.py

      - name: Configurar Git
        run: |
          git config --global user.name "Pulpo Paul Bot"
          git config --global user.email "bot@users.noreply.github.com"

      - name: Registrar y subir cambios
        run: |
          git add historico_mensual/ logs/ resultados/ kpi/ config/
          git status
          if git diff --staged --quiet; then
            echo "No hay cambios para guardar."
          else
            git commit -m "🤖 Actualización automática de resultados y proyecciones [skip ci]"
            git push
          fi
