name: Pulpo Paul Diario

on:
  workflow_dispatch:
  #schedule:
    # 1. Turno Mañana (Apertura Europa): 12:30 UTC (08:00 hrs de Chile)
    #- cron: '0 12 * * *'
    
    # 2. Turno Mediodía (Cierre Europa): 16:30 UTC (12:00 hrs de Chile)
    #- cron: '0 16 * * *'

    # 3. Turno Latam (Sudamérica/MLS): 19:30 UTC (15:00 hrs de Chile)
    #- cron: '0 19 * * *'

    # 4. Turno Nocturno (Proyección AM): 02:00 UTC (21:00 hrs de Chile)
    #- cron: '0 1 * * *'

jobs:
  analizar_partidos:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Necesario para el git push final

    steps:
      - name: Descargar el repositorio
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar el Pulpo Paul
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          API_FOOTBALL_KEY: ${{ secrets.API_FOOTBALL_KEY }}
          API_BASKETBALL_KEY: ${{ secrets.API_BASKETBALL_KEY }}
          TELEGRAM_BOT_TOKEN_BASKET: ${{ secrets.TELEGRAM_BOT_TOKEN_BASKET }}
        run: python main.py

      - name: Configurar Git
        run: |
          git config --global user.name "Pulpo Paul Bot"
          git config --global user.email "bot@users.noreply.github.com"

      - name: Registrar y subir cambios
        run: |
          git add historico_mensual/ logs/ resultados/
          git status
          # Verificamos si hay cambios pendientes para commitear
          if git diff --staged --quiet; then
            echo "No hay cambios para guardar."
          else
            git commit -m "🤖 Actualización automática de resultados y proyecciones [skip ci]"
            git push
          fi
